### ISSUE TITLE
Help: I am having .otf file how to convert in .fnt pleas show some lights on it

### ISSUE THREAD

**Issue by veerviren** [jarmoruuth/ClockJx#1]

**Comment by jarmoruuth** [comment]
Hi, Unfortunately I do not know the latest in Garmin development as I have not been doing anything here for a long time. But Garmin has good tools so you should go and check their site.

Regards,
Jarmo

**Comment by veerviren** [comment]
Thanks @jarmoruuth for your quick response please make this open until someone share the info or i will figure it out.

**Comment by jarmoruuth** [comment]
Closing.
